services:
  fsp:
    image: jacobneiltaylor/fspd:latest
    restart: unless-stopped
    ports:
      - "21:21/udp"
    volumes:
      - "${FSPD_CONF_FILE:-./fspd.conf}:/usr/local/etc/fspd.conf:ro"
      - "${FSPD_DATA_DIR:-./data}:/fsp:${FSPD_DATA_MODE:-ro}"