services:
  fsp:
    image: jacobneiltaylor/fspd:latest
    restart: unless-stopped
    ports:
      - "21:21/udp"
    volumes:
      - "./fspd.conf:/usr/local/etc/fspd.conf:ro"
      - "./data:/fsp:ro"